name: Stylelint

on:
  -push
  -pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
        - uses: actions/chekout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: npm install
          run: |
            make install
          env: 
            CI: true
        - name: Run stylelint
          run: |
            make stylelint